name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
  runs-on: ubuntu-latest
  steps:
    - name:Print Gree
      run: echo "Hello World"
    - name: Print bybye
      run :echo "Done -bye"
